//! Classify files as skip candidates (generated, minified, or vendored).
//!
//! Returns a short reason string so callers can surface these files to users
//! without requiring them to open each file to discover they are auto-generated
//! or vendored noise.

const GENERATED_SUFFIXES: &[&str] = &[
    ".pb.go",
    "_pb2.py",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".freezed.dart",
    ".designer.cs",
    ".generated.ts",
];
const VENDORED_DIRS: &[&str] = &[
    "vendor",
    "node_modules",
    "third_party",
    "third-party",
    "dist",
    "build",
    ".next",
    "out",
];

/// Return a reason string if `rel_path`/`content` looks like a file an agent
/// should skip, or `None` if it appears to be hand-authored source code.
///
/// Checks are applied in priority order: minified → generated → vendored.
#[must_use]
pub fn skip_hint(rel_path: &str, content: &str) -> Option<String> {
    // 1. Minified: .min. filename, very long lines, or high average line length.
    let filename = rel_path.rsplit('/').next().unwrap_or(rel_path);
    if filename.contains(".min.") {
        return Some("minified".to_string());
    }
    let lines: Vec<&str> = content.lines().collect();
    let line_count = lines.len();
    let longest = lines.iter().map(|l| l.len()).max().unwrap_or(0);
    if longest > 2000 {
        return Some("minified".to_string());
    }
    if line_count > 1 {
        let total: usize = lines.iter().map(|l| l.len()).sum();
        if total > line_count.saturating_mul(250) {
            return Some("minified".to_string());
        }
    }

    // 2. Generated: header keywords in the first 5 non-empty lines, or a
    //    well-known generated-file extension.
    for suffix in GENERATED_SUFFIXES {
        if rel_path.ends_with(suffix) {
            return Some("generated".to_string());
        }
    }
    for line in content.lines().filter(|l| !l.trim().is_empty()).take(5) {
        if is_generated_header(line) {
            return Some("generated".to_string());
        }
    }

    // 3. Vendored: a well-known vendor/build directory appears as a whole path
    //    component. Matching whole segments avoids false positives like
    //    `rebuild/` (contains "build") or `layout/` (contains "out").
    let normalized = rel_path.replace('\\', "/");
    let mut components: Vec<&str> = normalized.split('/').collect();
    components.pop(); // drop the filename; only directory components count
    if components.iter().any(|c| VENDORED_DIRS.contains(c)) {
        return Some("vendored".to_string());
    }

    None
}

/// Match canonical generated-file comment headers, not incidental prose such
/// as documentation describing generated code.
fn is_generated_header(line: &str) -> bool {
    let line = line.trim_start();
    let comment = line
        .strip_prefix("//")
        .or_else(|| line.strip_prefix('#'))
        .or_else(|| line.strip_prefix("/*"))
        .map(str::trim_start);
    let Some(comment) = comment else {
        return false;
    };
    let lower = comment.to_ascii_lowercase();
    lower.starts_with("@generated")
        || lower.starts_with("code generated by")
        || lower.starts_with("this file was generated")
        || lower.starts_with("this file is generated")
        || lower.starts_with("automatically generated")
        || lower.starts_with("auto-generated")
        || (lower.starts_with("generated") && lower.contains("do not edit"))
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn long_single_line_is_minified() {
        let long_line = "a".repeat(2001);
        assert_eq!(
            skip_hint("bundle.js", &long_line),
            Some("minified".to_string())
        );
    }

    #[test]
    fn min_dot_filename_is_minified() {
        assert_eq!(
            skip_hint("jquery.min.js", "x=1"),
            Some("minified".to_string())
        );
    }

    #[test]
    fn generated_comment_header_is_detected() {
        let content = "// Code generated by protoc. DO NOT EDIT.\nfoo();";
        // Use a plain .go path so the path-suffix check doesn't fire first.
        assert_eq!(skip_hint("foo.go", content), Some("generated".to_string()));
    }

    #[test]
    fn prose_about_generated_code_is_not_a_generated_header() {
        let content =
            "//! Classify files as skip candidates.\n//! Auto-generated code can be noisy.";
        assert_eq!(skip_hint("src/classify.rs", content), None);
    }

    #[test]
    fn generated_path_suffix_is_detected() {
        assert_eq!(
            skip_hint("api/types.pb.go", "package api"),
            Some("generated".to_string())
        );
    }

    #[test]
    fn vendored_path_is_detected() {
        assert_eq!(
            skip_hint("node_modules/foo/bar.js", "let x = 1;"),
            Some("vendored".to_string())
        );
    }

    #[test]
    fn similar_named_dirs_are_not_vendored() {
        // Whole-segment matching: these contain vendor-dir substrings but are
        // ordinary source directories, so they must NOT be flagged.
        assert_eq!(skip_hint("src/rebuild/step.rs", "fn f() {}"), None);
        assert_eq!(skip_hint("app/layout/main.ts", "const x = 1;"), None);
        assert_eq!(skip_hint("workout/plan.py", "x = 1"), None);
    }

    #[test]
    fn ordinary_code_is_none() {
        let content = "fn main() { println!(\"hello\"); }";
        assert_eq!(skip_hint("src/main.rs", content), None);
    }
}
